version: "3"

services:
  app:
    restart: always
    build: .
    env_file: .env
    container_name: dojo-v1-app
    command: invoke release start
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    container_name: dojo-v1-db
    ports:
      - "5432:5432"
