services:
  app:
    restart: always
    build: .
    env_file: .env
    container_name: dojo-v1-app
    command: invoke release start
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    container_name: dojo-v1-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15
