[tool]
[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
#default_section = "THIRDPARTY"
#known_first_party = []
#known_third_party = []
skip=['.eggs', '.git', '.hg', '.mypy_cache', '.nox', '.pants.d', '.tox', '.venv', '_build', 'buck-out', 'build', 'dist', 'node_modules', 'venv', 'migrations']

[tool.black]
line-length = 120
#target-version = ['py38']
#include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/

)
'''

[tool.poetry]
name = "we-all-code"
description = ""
version = "0.0.0"
license = "MIT"
readme = "README.md"
repository = "https://github.com/weallcode/website"
homepage = "https://github.com/weallcode/website"
authors = ["Ali Karbassi <ali@weallcode.org>"]

[tool.poetry.dependencies]
python = "3.9.1"
arrow = "^1.2.3"
boto3 = "^1.26.10"
Django = "^4.1"
django-allauth = "^0.51.0"
django-anymail = "^8.6"
django-appconf = "^1.0.5"
django-bootstrap3 = "^22.1"
django-cleanup = "^6.0.0"
django-common-helpers = "^0.9.2"
django-cron = "^0.6.0"
django-debug-toolbar = "^3.7.0"
django-environ = "^0.9.0"
django-fullurl = "^1.3"
django-heroku = "^0.3.1"
django-html5 = "^1.0.0"
django-import-export = "^3.0.1"
django-loginas = "^0.3.11"
django-meta = "^2.1.0"
django-nose = "^1.4.7"
django-recaptcha = "^3.0.0"
django-stdimage = "^6.0.1"
django-storages = "^1.13.1"
factory-boy = "^3.2.1"
gunicorn = "^20.1.0"
icalendar = "^5.0.2"
invoke = "^1.7.3"
json-logging-py = "^0.2"
mock = "^4.0.3"
Pillow = "^9.3.0"
psycopg2-binary = "^2.9.5"
sentry-sdk = "^1.11.0"
django-active-link = "^0.1.8"
