[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
force_grid_wrap = 2
use_parentheses = true
remove_redundant_aliases = true
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
skip_gitignore = true
skip = [".gitignore", ".dockerignore", ".venv"]
skip_glob = "**/migrations/*.py"


[tool.black]
line_length = 79
target-version = ['py311']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/

)
'''

[tool.poetry]
name = "we-all-code"
description = ""
version = "0.0.1"
license = "MIT"
readme = "README.md"
repository = "https://github.com/weallcode/website"
homepage = "https://github.com/weallcode/website"
authors = ["Ali Karbassi <ali@weallcode.org>"]

[tool.poetry.dependencies]
python = "3.11.3"
arrow = "^1.3.0"
boto3 = "^1.28.62"
django = "^4.2"
django-active-link = "^0.1.8"
django-allauth = "^0.57.0"
django-anymail = "^10.1"
django-appconf = "^1.0.5"
django-bootstrap3 = "^23.4"
django-cleanup = "^8.0.0"
django-common-helpers = "^0.9.2"
django-cron = "^0.6.0"
django-debug-toolbar = "^4.2.0"
django-environ = "^0.11.2"
django-fullurl = "^1.4"
django-heroku = "^0.3.1"
django-html5 = "^1.0.0"
django-import-export = "^3.3.1"
django-loginas = "^0.3.11"
django-meta = "^2.4.0"
django-nose = "^1.4.7"
django-recaptcha = "^3.0.0"
django-stdimage = "^6.0.1"
django-storages = "^1.14"
factory-boy = "^3.3.0"
gunicorn = "^21.2.0"
icalendar = "^5.0.7"
invoke = "^2.2.0"
json-logging-py = "^0.2"
mock = "^5.1.0"
pillow = "^10.0.1"
psycopg = {extras = ["binary"], version = "^3.1.10"}
sentry-sdk = "^1.31.0"
