name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      # - uses: pre-commit/action@v3.0.0

      - run: python -m pip install pre-commit
        shell: bash

      - run: python -m pip freeze --local
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
        shell: bash

      - name: Commit changes
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":art: Running pre-commit hooks"
